###
GET http://localhost:3000/
###

POST http://localhost:3000
Content-Type: application/json

{
    "action": "lowercase",
    "input": "Lorem Ipsum"
}
###
POST http://localhost:3000
Content-Type: application/json

{
    "action": "UpperCase",
    "input": "Lorem Ipsum"
}

