###
GET http://localhost:3000/
###

POST http://localhost:3000/text/lowercase
Content-Type: application/json
{
    "input": "Lorem Ipsum"
}
###
POST http://localhost:3000/text/uppercase
Content-Type: application/json

{
    "input": "Lorem Ipsum"
}
###

POST http://localhost:3000/number/minimum/?input=10,1,100
 
###
POST http://localhost:3000/number/maximum/?input=10,1,100
